runtime: python39

entrypoint: gunicorn -b :$PORT LiveGuard_backend.wsgi

handlers:
  - url: /static
    static_dir: staticfiles/
  - url: /.*
    script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: LiveGuard_backend.settings
  DEBUG: 'False'

automatic_scaling:
  min_instances: 1
  max_instances: 5
